### ISSUE TITLE
I stage

### ISSUE THREAD

**Issue by rusdevops** [Niyaz97/Stack#1]
@Niyaz97 

- [x] 1. Присутствует определение избыточной цели. [здесь](https://github.com/Niyaz97/Stack/blob/2a5304787426ada24c9c8c7544020d7e663586fe/CMakeLists.txt#L14).
- [x] 2. Присутствует избыточное подключение заголовочного файла. [здесь](https://github.com/Niyaz97/Stack/blob/2a5304787426ada24c9c8c7544020d7e663586fe/include/stack.hpp#L4).

**Comment by Niyaz97** [comment]
closed in [this](https://github.com/Niyaz97/Stack/commit/aba753cf6ade6d2ffb2b40c0123ae5ab5171a2c0) commit
